OnlineExamWeb/Controllers/ExamController.cs
using Exam.Core.Domain.Abstract;
using Exam.Core.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineExamWeb.Helpers;
using OnlineExamWeb.Mappers;
using OnlineExamWeb.Models;
using OnlineExamWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineExamWeb.Controllers
{
    [Authorize(Roles = "SA,A")]
    public class ExamController : BaseController
    {
        public ExamController (IUnitOfWork db,UserManager<User> userManager) : base(db, userManager) { }

        public IActionResult Index()
        {
            ViewBag.Message = TempData["Message"];

            List<Exam1> exams = DB.ExamRepository.Get();
            ExamViewModel examViewModel = new ExamViewModel();
            ExamMapper examMapper = new ExamMapper();

            foreach(var exam in exams)
            {
                var examModel = examMapper.Map(exam);
                examViewModel.Exams.Add(examModel);
            }
            EnumerationUtil.Enumerate(examViewModel.Exams);

            return View(examViewModel);
        }

        [HttpGet]
        public IActionResult SaveExam(int ID)
        {
            if(ID!=0)
            {
                Exam1 exam = DB.ExamRepository.Get(ID);

                if(exam==null)
                {
                    return Content("İmtahan növü tapılmadı");
                }
                ExamMapper examMapper = new ExamMapper();
                ExamModel examModel = examMapper.Map(exam);

                return View(examModel);
            }
            return View(new ExamModel());
        }

        
        [HttpPost]
        public IActionResult SaveExam(ExamModel examModel)
        {
            if (!ModelState.IsValid)
            {
                return Content(UiMessages.WrongMessage);
            }

            ExamMapper examMapper = new ExamMapper();
            Exam1 exam = examMapper.Map(examModel);
            exam.Creator = CurrentUser;

            if(exam.ID!=0)
            {
                DB.ExamRepository.Update(exam);
                TempData["Message"] = UiMessages.SuccesMessage;
            }
            else
            {
                DB.ExamRepository.Add(exam);
                TempData["Message"] = UiMessages.SuccesMessage;
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete (ExamViewModel examViewModel)
        {
            Exam1 exam = DB.ExamRepository.Get(examViewModel.DeletedID);

            if(exam==null)
            {
                return Content("İmtahan növü tapılmadı");
            }

            exam.Creator = CurrentUser;
            exam.IsDeleted = true;

            DB.ExamRepository.Update(exam);

            TempData["Message"] = UiMessages.SuccesMessage;

            return RedirectToAction("Index");
        }
    }
}

OnlineExamWeb/Controllers/QuestionController.cs
using Exam.Core.Domain.Abstract;
using Exam.Core.Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using OnlineExamWeb.Mappers;
using OnlineExamWeb.ViewModels;
using System.Collections.Generic;
using OnlineExamWeb.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using OnlineExamWeb.Helpers;
using System.Text;

namespace OnlineExamWeb.Controllers
{
    [Authorize(Roles = "SA,A")]
    public class QuestionController : BaseController
    {
        public QuestionController(IUnitOfWork db, UserManager<User> userManager) : base(db, userManager) { }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Message = TempData["Message"];

            List<Question> questions = DB.QuestionRepository.Get();

            QuestionViewModel questionViewModel = new QuestionViewModel();

            QuestionMapper questionMapper = new QuestionMapper();

            foreach (var question in questions)
            {
                var questionModel = questionMapper.Map(question);
                questionViewModel.Questions.Add(questionModel);
            }

            EnumerationUtil.Enumerate(questionViewModel.Questions);

            return View(questionViewModel);

        }

        [HttpGet]
        public IActionResult SaveQuestion(int id)
        {
            QuestionModel questionModel = new QuestionModel();

            if (id != 0)
            {
                Question question = DB.QuestionRepository.FindByID(id);
                if (question == null)
                {
                    return Content("Sual Tapılmadı");
                }
                QuestionMapper questionMapper = new QuestionMapper();
                questionModel = questionMapper.Map(question);
            }

            List<Subject> subjects = DB.SubjectRepository.Get();
            List<SelectListItem> subjectModels = new List<SelectListItem>();

            foreach (var subject in subjects)
            {
                subjectModels.Add(new SelectListItem(subject.Name, subject.ID.ToString()));
            }

            List<Exam1> exams = DB.ExamRepository.Get();
            List<SelectListItem> examModels = new List<SelectListItem>();

            foreach (var exam in exams)
            {
                examModels.Add(new SelectListItem(exam.ExamType, exam.ID.ToString()));
            }

            questionModel.Subjects = subjectModels;
            questionModel.Exams = examModels;

            return View(questionModel);
        }

        [HttpPost]
        public IActionResult SaveQuestion(QuestionModel questionModel)
        {
            if (ModelState.IsValid == false)
            {
                StringBuilder sb = new StringBuilder();

                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        sb.AppendLine(error.ErrorMessage);
                    }
                }

                return Content(sb.ToString());
            }

            QuestionMapper questionMapper = new QuestionMapper();
            Question question = questionMapper.Map(questionModel);
            question.Creator = CurrentUser;

            if(question.ID !=0)
            {
                DB.QuestionRepository.Update(question);
                TempData["Message"] = UiMessages.SuccesMessage;
            }
            else
            {
                DB.QuestionRepository.Add(question);
                TempData["Message"] = UiMessages.SuccesMessage;

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(QuestionViewModel questionViewModel)
        {
            Question question = DB.QuestionRepository.FindByID(questionViewModel.DeletedID);

            if (question == null)
            {
                return Content("Sual Tapılmadı");
            }

            question.LastModifiedDate = DateTime.Now;
            question.IsDeleted = true;
            question.Creator = CurrentUser;

            DB.QuestionRepository.Update(question);

            TempData["Message"] = UiMessages.SuccesMessage;

            return RedirectToAction("Index");
        }
    }
}

OnlineExamWeb/Controllers/SubjectController.cs
using Exam.Core;
using Exam.Core.Domain.Abstract;
using Exam.Core.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineExamWeb.Helpers;
using OnlineExamWeb.Mappers;
using OnlineExamWeb.Models;
using OnlineExamWeb.ViewModels;
using System.Collections.Generic;

namespace OnlineExamWeb.Controllers
{
    [Authorize(Roles="SA,A")]
    public class SubjectController : BaseController
    {
        public SubjectController(IUnitOfWork db, UserManager<User> userManager) : base(db, userManager) { }

        public IActionResult Index()
        {
            ViewBag.Message = TempData["Message"];

            List<Subject> subjects = DB.SubjectRepository.Get();

            SubjectViewModel subjectViewModel = new SubjectViewModel();

            SubjectMapper subjectMapper = new SubjectMapper();

            foreach(var subject in subjects)
            {
                var subjectModel = subjectMapper.Map(subject);
                subjectViewModel.Subjects.Add(subjectModel);
            }

            EnumerationUtil.Enumerate(subjectViewModel.Subjects);

            return View(subjectViewModel);
        }

        [HttpGet]
        public IActionResult SaveSubject(int ID)
        {
            if(ID!=0)
            {
                Subject subject = DB.SubjectRepository.Get(ID);

                if(subject==null)
                {
                    return Content("Fənn Tapılmadı");
                }

                SubjectMapper subjectMapper = new SubjectMapper();
                SubjectModel subjectModel = subjectMapper.Map(subject);

                return View(subjectModel);
            }
            return View(new SubjectModel());
        }

        [HttpPost]
        public IActionResult SaveSubject(SubjectModel subjectModel)
        {
            if(!ModelState.IsValid)
            {
                return Content(UiMessages.WrongMessage);
            }

            SubjectMapper subjectMapper = new SubjectMapper();
            Subject subject = subjectMapper.Map(subjectModel);
            subject.Creator = CurrentUser;

            if(subject.ID!=0)
            {
                DB.SubjectRepository.Update(subject);
                TempData["Message"] = UiMessages.SuccesMessage;
            }
            else
            {
                DB.SubjectRepository.Add(subject);
                TempData["Message"] = UiMessages.SuccesMessage;
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(SubjectViewModel subjectViewModel)
        {
            Subject subject = DB.SubjectRepository.Get(subjectViewModel.DeletedID);

            if (subject == null)
            {
                return Content("Fənn Tapılmadı");
            }

            subject.Creator = CurrentUser; 
            subject.IsDeleted = true;

            DB.SubjectRepository.Update(subject);

            TempData["Message"] = UiMessages.SuccesMessage;
            return RedirectToAction("Index");
        }
    }
}

OnlineExamWeb/Views/Shared/Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @*<title>Subjects</title>*@

    <link rel="stylesheet" type="text/css" media="screen" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="~/css/layout.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/css/commonDesign.css">
    <link rel="stylesheet" href="~/css/warninganimation.css">
    <link rel="stylesheet" href="~/DataTables/datatables.min.css" />
    <script type="text/javascript" src="~/DataTables/datatables.min.js"></script>
</head>

<body style="overflow-x:hidden;overflow-y:auto">
    <nav class="navbar navbar-expand-md navbar-dark shadow fixed-top bg-dark flex-md-nowrap justify-content-between">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">@User.Identity?.Name</a>
        <div>
            <button class="navbar-toggler" id="btn-toggler" type="button" data-toggle="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a asp-controller="Account" asp-action="Logout" class="btn btn-outline-light">Sign out</a>
        </div>
    </nav>

    <div style="height:100vh;">
        <div class="container-flud h-100" style="padding-top:56px;">
            <div class="row h-100">
                <div id="sidebar" class="col-sm-12 col-md-3 col-lg-2 col-xl-2">
                    <div class="list-group list-group-flush">

                        <a asp-controller="Subject" asp-action="Index" class="sequence list-group-item list-group-item-action">Fənlər</a>
                        <a asp-controller="Exam" asp-action="Index" class="sequence list-group-item list-group-item-action">İmtahanlar</a>
                        <a asp-controller="Question" asp-action="Index" class="sequence list-group-item list-group-item-action">Suallar</a>
                    </div>
                </div>
                <div id="content" class="col-sm-12 col-md-9 col-lg-10 col-xl-10 p-0">
                    <div id="content-header" class="w-100 text-white p-2 bg-info shadow">Test</div>
                    <div>

                        <div class="container mb-3 mt-3" style="margin:25px;">
                            <h1 style="text-align: center;">@ViewData["Title"]</h1>

                            @if (ViewBag.Message != null)
                            {
                                <div class="divAnim">@ViewBag.Message</div>
                            }

                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            switch (window.location.pathname.split('/')[1]) {
                case 'Subject':
                    {
                        $('.sequence').eq(0).addClass('active text-white');
                        $('#content-header').text('Fənlər');
                        break;
                    }
                case "Exam":
                    {
                        $('.sequence').eq(1).addClass('active text-white');
                        $('#content-header').text('İmtahanlar');
                        break;
                    }
                case 'Question':
                    {
                        $('.sequence').eq(2).addClass('active text-white');
                        $('#content-header').text('Suallar');
                        break;
                    }
                default:
                    {
                        $('.sequence').eq(0).addClass('active text-white');
                        $('#content-header').text('Fənlər');
                        break;
                    }
            }

            $('#btn-toggler').click(function () {
                $('#sidebar').eq(0).slideToggle();
            });
        });

        var toggler = document.getElementsByClassName("caret");
        var i;

        for (i = 0; i < toggler.length; i++) {
            toggler[i].addEventListener("click", function () {
                this.parentElement.querySelector(".nested").classList.toggle("active");
                this.classList.toggle("caret-down");
            });
        }

        $(document).ready(function () {
            $('#example').dataTable();
        });

        function ShowDeleteModal(id) {
            $("#DeletedID").val(id);
        }
    </script>
</body>
</html>